### PR TITLE
Initial draft of flow SLA

### PR DESCRIPTION
**Pull request by mbryzek**

### CODE REVIEW

**Comment by mikeclimbrock** [comment]
lgtm

**Comment by rkeve** [comment]
Somewhere in the doc please create a defined term of Subscription
Subscription - subscription fee for hosting the corporate instance of Flow 

ie we need to distinguish between some parts of the fee and all of it - eg in Gilt's case the fee includes 3rd party costs (shipping, fraud, payment processing etc) we cant give credits against these costs. Hence my trying to narrow the refund to just being a 'hosting element' of our overall fee

**Comment by mbryzek** [comment]
Added:

  - Monthly Subscription Fee means the total platform subscription fee
    as defined in the Agreement in a calendar month. Broadly speaking,
    this includes the specific monthly fee for access to the Flow
    Commerce Platform, excluding pass through fees including but not
    limited to credit card processing fees, shipping costs, etc.

**Comment by rkeve** [comment]
The upside of this is it's clear and transparent.   Downside is those fees are not necessarily pass throughs so may beg questions about our costs.

**Comment by mbryzek** [comment]
any thoughts on how we might make clearer?

**Comment by rkeve** [comment]
three options - neither great

1. We do what I had suggested and just make the % of the Flow Hosting fee (albeit we havent defined what/how much that would be - and is largely created just for this purpose) 
2. We offer a flat rate penalty eg $1k, $5k  (not %s) 
3. We have different versions of the T&Cs depending on whether we are including services with 3rd parties or not and setting the %s accordingly

**Comment by mbryzek** [comment]
1. Not sure how to define "% of the Flow Hosting fee"
2. not a fan of flat rate (and larger orgs may force us to change) 
3. not excited to manage multiple SLAs

In the original version I had written:

  - Monthly Subscription Fee means the total platform subscription fee
    as defined in the Agreement in a calendar month.

This specifically makes it clear the subscription fee would be defined in the agreement (and thus we delay until agreement time what is included).

What if we amend this slightly to add "excluding any 3rd party fees", i.e:

  - Monthly Subscription Fee means the total platform subscription fee
    excluding any 3rd party fees as defined in the Agreement in a calendar month.

**Comment by rkeve** [comment]
right - fine with the concept of punting and excluding 3rd party fees - lets also make it a subset of ‘subscription’ in case we need wiggle room. eg Platform Subscription or Module Subscription or Product Subscription (so we can constrast it with another form of subscription if we need to).

**Comment by mbryzek** [comment]
great - have updated to read:

  - Monthly Subscription Fee means the total platform subscription or
    module subscription or product subscription fee as defined in the
    Agreement in a calendar month.

**Comment by rkeve** [comment]
i meant we should chose one of those and just insert into the SLA bt not define it until we are ready in contracts. 

eg if we breach 99.9% for X time period you get credits equivalent to X of the Platform Subscription fee

**Pull request merged**
